name: bmad-godot-game-dev
version: 1.0.0
short-title: Godot GDScript Game Dev Pack
description: Game Development expansion pack for BMad Method - Godot & GDScript focused for 2D and 3D games
author: TheCircus
slashPrefix: bmadg
